<<<<<<< HEAD
name: mlops-exaple-tensorflow-regression
=======
name: MLOps-offline_regression_testing
>>>>>>> dab5408b09e2f2b0bf51722cb923e199f8458931
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Train my model'
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
<<<<<<< HEAD
          python FH_Pipeline2.py
          
          echo "## Model Metrics" > report.md
          cat metrics.txt >> report.md
          
          echo "\n## Model Performance" >> report.md
          echo "Model performance metrics are on the plot below." >> report.md
          
          cml-publish mindaffectBCI_decoding_curve.png --md >> report.md
          
=======
          pip install --upgrade pip
          pip install -e .
          
          python mindaffectBCI/decoder/offline_regression_testing.py
          python csv2text.py
          
          echo "## OFFLINE REGRESSION TESTING" > report.md
          cat metrics.txt >> report.md
          
>>>>>>> dab5408b09e2f2b0bf51722cb923e199f8458931
          cml-send-comment report.md
